"""Update relationships between models version3

Revision ID: 928ca39faca6
Revises: a0c18c417d3e
Create Date: 2024-07-29 21:49:47.492562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928ca39faca6'
down_revision = 'a0c18c417d3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
