"""Update relationships between models version2

Revision ID: a0c18c417d3e
Revises: ac1710cb3936
Create Date: 2024-07-29 21:48:05.658188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c18c417d3e'
down_revision = 'ac1710cb3936'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
