"""Update relationships between models

Revision ID: ac1710cb3936
Revises: b1f53ed0f66d
Create Date: 2024-07-29 21:29:14.695166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1710cb3936'
down_revision = 'b1f53ed0f66d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
