"""Update model relationships

Revision ID: b1f53ed0f66d
Revises: 4af4b2427887
Create Date: 2024-07-29 21:21:57.454050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f53ed0f66d'
down_revision = '4af4b2427887'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
